export const contributorsList = [
  {
    first_name: 'John',
    last_name: 'Doe',
    email: 'pkmiracle36@gmail.com',
    amount: 100,
    thoughts:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam delectus tenetur quasi in blanditiis at, debitis architecto dicta velit! Sequi laborum eum, quibusdam iste, quos incidunt corrupti voluptas cupiditate a pariatur doloremque perferendis accusantium ipsum delectus illo nobis facere eaque, corporis eveniet voluptate tenetur impedit laboriosam minus doloribus. Aspernatur, nihil?',
    date: '2024-10-05',
    contributionsCount: 1,
    publish_name: false,
  },
  {
    name: 'Jane Smith',
    amount: 50,
    thoughts: 'Praying for your success!',
    date: '2024-10-03',
    contributionsCount: 3,
  },
  {
    name: 'Sam Wilson',
    amount: 75,
    thoughts: 'Glad to contribute!',
    date: '2024-10-02',
    contributionsCount: 5,
  },
  {
    name: 'Emily Clarke',
    amount: 200,
    thoughts: 'Proud to be a part of this!',
    date: '2024-10-04',
    contributionsCount: 1,
  },
  {
    name: 'Michael Johnson',
    amount: 150,
    thoughts: 'Best of luck!',
    date: '2024-09-29',
    contributionsCount: 2,
  },
  {
    name: 'Linda Brown',
    amount: 120,
    thoughts: 'Happy to help!',
    date: '2024-09-28',
    contributionsCount: 4,
  },
  {
    name: 'Chris Evans',
    amount: 90,
    thoughts: 'Supporting this great cause!',
    date: '2024-10-01',
    contributionsCount: 1,
  },
  {
    name: 'John Doe',
    amount: 100,
    thoughts: 'Excited to support this project!',
    date: '2024-10-05',
    contributionsCount: 1,
  },
  {
    name: 'Jane Smith',
    amount: 50,
    thoughts: 'Praying for your success!',
    date: '2024-10-03',
    contributionsCount: 3,
  },
  {
    name: 'Sam Wilson',
    amount: 75,
    thoughts: 'Glad to contribute!',
    date: '2024-10-02',
    contributionsCount: 5,
  },
  {
    name: 'Emily Clarke',
    amount: 200,
    thoughts: 'Proud to be a part of this!',
    date: '2024-10-04',
    contributionsCount: 1,
  },
  {
    name: 'Michael Johnson',
    amount: 150,
    thoughts: 'Best of luck!',
    date: '2024-09-29',
    contributionsCount: 2,
  },
  {
    name: 'John Doe',
    amount: 100,
    thoughts: 'Excited to support this project!',
    date: '2024-10-05',
    contributionsCount: 1,
  },
  {
    name: 'Jane Smith',
    amount: 50,
    thoughts: 'Praying for your success!',
    date: '2024-10-03',
    contributionsCount: 3,
  },
  {
    name: 'Sam Wilson',
    amount: 75,
    thoughts: 'Glad to contribute!',
    date: '2024-10-02',
    contributionsCount: 5,
  },
  {
    name: 'Emily Clarke',
    amount: 200,
    thoughts: 'Proud to be a part of this!',
    date: '2024-10-04',
    contributionsCount: 1,
  },
  {
    name: 'Michael Johnson',
    amount: 150,
    thoughts: 'Best of luck!',
    date: '2024-09-29',
    contributionsCount: 2,
  },
];

export const wordsToShow = 4;
